openapi: 3.0.3
info:
  title: Webhook API
  description: Este projeto tem como finalidade disponibilizar endpoints e modelar payloads para deixar compatível a integração com leads-delivery
  version: 1.0.0
servers:
- url: /api/webhooks/v1
 
paths:
  
  /mercado-livre:
    post:
      tags:
        - Mercado Livre
      summary: Return code 200
      description: Endpoint pra integração da aplicação casa mineira com mercado livre
      operationId: sendLeadFromMercadoLivre
      requestBody:
        required: true
        description: Lead enviado pela origem
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: number

  /info:
    get:
      tags:
        - Mercado Livre
      summary: Return code 200
      description: Endpoint pra integração da aplicação casa mineira com mercado livre
      operationId: getInfo
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: number

  /calcular-soma:
    
    get:
      tags:
        - Calculos
      summary: Return code 200
      description: Endpoint para somar dois valores
      operationId: getcalculos
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: number

  /movies:
   get:
    tags:
      - lista de filmes
    summary: Return code 200
    description: Endpoint para listar filmes
    operationId: getMovies
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  year:
                    type: integer
                  genre:
                    type: string

  /clima:
   get:
    tags:
      - clima da cidade
    summary: Return code 200
    description: Endpoint ver o clima de uma cidade
    operationId: getClima
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  city:
                    type: string
                  temperature:
                    type: integer
                  description:
                    type: string
                  humidity:
                    type: integer   

  /users:
    post:
      tags:
        - Users
      summary: Create a new user
      description: Endpoint para criar um novo usuário na aplicação.
      operationId: addUser
      requestBody:
        required: true
        description: Dados do usuário a ser criado
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nome do usuário
                email:
                  type: string
                  description: E-mail do usuário
                password:
                  type: string
                  description: Senha do usuário
                age:
                  type: number
                  description: idade do usuario
              required:
                - name
                - email
                - password
                - age
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
        500:
          description: Error
          content:
            application/json:
              schema:
                type: object

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
